services:
  - type: web
    name: yui
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    pythonVersion: 3.11.9
runtime: python
